### ISSUE TITLE
AttributeError: 'MessagesMessage' object has no attribute 'message'

### ISSUE THREAD

**Issue by bgrebennikov** [fscdev/vkwave#107]
Делал бота на основе примера https://github.com/kesha1225/VkWaveBotExample

Сам бот работает, но в консоле все равно появляется куча ошибок, на которые не очень приятно смотреть. 
```

Task exception was never retrieved
future: <Task finished name='Task-54' coro=<Dispatcher.process_event() done, defined at /Users/imac/Desktop/vkbot/botenv/lib/python3.9/site-packages/vkwave/bots/core/dispatching/dp/dp.py:41> exception=AttributeError("'MessagesMessage' object has no attribute 'message'")>
Traceback (most recent call last):
  File "/Users/imac/Desktop/vkbot/botenv/lib/python3.9/site-packages/vkwave/bots/core/dispatching/dp/dp.py", line 66, in process_event
    if not await self.middleware_manager.execute_pre_process_event(event):
  File "/Users/imac/Desktop/vkbot/botenv/lib/python3.9/site-packages/vkwave/bots/core/dispatching/dp/middleware/middleware.py", line 27, in execute_pre_process_event
    m_res = await middleware.pre_process_event(event)
  File "/Users/imac/Desktop/vkbot/middlewares/user_data_middleware.py", line 10, in pre_process_event
    user_id = event.object.object.message.from_id
AttributeError: 'MessagesMessage' object has no attribute 'message'
Task exception was never retrieved
future: <Task finished name='Task-59' coro=<Dispatcher.process_event() done, defined at /Users/imac/Desktop/vkbot/botenv/lib/python3.9/site-packages/vkwave/bots/core/dispatching/dp/dp.py:41> exception=AttributeError("'MessagesMessage' object has no attribute 'message'")>
Traceback (most recent call last):
  File "/Users/imac/Desktop/vkbot/botenv/lib/python3.9/site-packages/vkwave/bots/core/dispatching/dp/dp.py", line 66, in process_event
    if not await self.middleware_manager.execute_pre_process_event(event):
  File "/Users/imac/Desktop/vkbot/botenv/lib/python3.9/site-packages/vkwave/bots/core/dispatching/dp/middleware/middleware.py", line 27, in execute_pre_process_event
    m_res = await middleware.pre_process_event(event)
  File "/Users/imac/Desktop/vkbot/middlewares/user_data_middleware.py", line 10, in pre_process_event
    user_id = event.object.object.message.from_id
AttributeError: 'MessagesMessage' object has no attribute 'message'

```

При этом бот отвечает на сообщения, но при каждом новом сообщении выходит это.

**Comment by kesha1225** [comment]
Скорее всего пришел эвент без сообщения, это нормально
