### ISSUE TITLE
Не работает callback

### ISSUE THREAD

**Issue by Masynchin** [fscdev/vkwave#119]
Скопировал пример из https://github.com/fscdev/vkwave/blob/master/examples/bots/simple_cb_api.py

**Comment by Masynchin** [comment]
Traceback (most recent call last):
  File "main.py", line 20, in <module>
    bot.run_forever()
  File "C:\herobot\env\lib\site-packages\vkwave\bots\addons\easy\base_easy_bot.py", line 198, in run_forever
    loop.create_task(self.run(ignore_errors))
TypeError: run() takes 1 positional argument but 2 were given
Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x03587058>
