### ISSUE TITLE
[БАГ]: Исключение при попытке сделать импорт библиотеки

### ISSUE THREAD

**Issue by Lonely-Dark** [fscdev/vkwave#188]
## Чеклист

- [x] Я убедился, что похожая проблема еще не была описана

- VKWave установлен из (выберите один вариант)
  - [x] PyPI
  - [x] Github

## Описание
Когда пытаюсь просто импортнуть обычного бота(SimpleLongPollBot) выскакивает ошибка(установлено через poetry)
Тестировал как через PyPi, так и через GitHub, ошибка одна и та же.

## Трейсбек (лог с ошибкой)

```python
Traceback (most recent call last):
  File "C:\Users\Bit\PycharmProjects\test_timetable\main.py", line 1, in <module>
    from vkwave.bots import SimpleLongPollBot
  File "C:\Users\Bit\AppData\Local\pypoetry\Cache\virtualenvs\test-timetable-9v-t2yrb-py3.11\Lib\site-packages\vkwave\bots\__init__.py", line 1, in <module>
    from .core.dispatching.dp.dp import Dispatcher
  File "C:\Users\Bit\AppData\Local\pypoetry\Cache\virtualenvs\test-timetable-9v-t2yrb-py3.11\Lib\site-packages\vkwave\bots\core\__init__.py", line 1, in <module>
    from .dispatching.dp.dp import Dispatcher  # noqa: F401
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Bit\AppData\Local\pypoetry\Cache\virtualenvs\test-timetable-9v-t2yrb-py3.11\Lib\site-packages\vkwave\bots\core\dispatching\dp\__init__.py", line 1, in <module>
    from .result_caster import BaseResultCaster, ResultCaster
  File "C:\Users\Bit\AppData\Local\pypoetry\Cache\virtualenvs\test-timetable-9v-t2yrb-py3.11\Lib\site-packages\vkwave\bots\core\dispatching\dp\result_caster.py", line 6, in <module>
    from vkwave.bots.core.dispatching.events.base import BaseEvent
  File "C:\Users\Bit\AppData\Local\pypoetry\Cache\virtualenvs\test-timetable-9v-t2yrb-py3.11\Lib\site-packages\vkwave\bots\core\dispatching\events\base.py", line 7, in <module>
    from vkwave.types.user_events import BaseUserEvent
  File "C:\Users\Bit\AppData\Local\pypoetry\Cache\virtualenvs\test-timetable-9v-t2yrb-py3.11\Lib\site-packages\vkwave\types\user_events.py", line 39, in <module>
    class MessageData(pydantic.BaseModel):
  File "C:\Users\Bit\AppData\Local\pypoetry\Cache\virtualenvs\test-timetable-9v-t2yrb-py3.11\Lib\site-packages\pydantic\main.py", line 292, in __new__
    cls.__signature__ = ClassAttribute('__signature__', generate_model_signature(cls.__init__, fields, config))
                                                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Bit\AppData\Local\pypoetry\Cache\virtualenvs\test-timetable-9v-t2yrb-py3.11\Lib\site-packages\pydantic\utils.py", line 258, in generate_model_signature
    merged_params[param_name] = Parameter(
                                ^^^^^^^^^^
  File "C:\Python311\Lib\inspect.py", line 2715, in __init__
    raise ValueError('{!r} is not a valid parameter name'.format(name))

```

## Код, вызвающий ошибку

```python
from vkwave.bots import SimpleLongPollBot
```
## Ожидаемое поведение
Импорт библиотеки для дальнейшего использования

**Comment by KurimuzonAkuma** [comment]
Обнови pydantic через pip install pydantic -U

**Comment by evtn** [comment]
> Обнови pydantic через pip install pydantic -U

У вас вот [тут](https://github.com/fscdev/vkwave/blob/master/pyproject.toml#L39) фиксируется pydantic<2.0, без проблем обновить не получится
