### ISSUE TITLE
Ошибка

### ISSUE THREAD

**Issue by sergeyfilippov1** [fscdev/vkwave#48]
Когда я пытаюсь запустить скрипт, где используются юзерботы, происходит ошибка

Код:
```
from vkwave.bots import SimpleLongPollUserBot, TaskManager, ClonesBot


bot = SimpleLongPollUserBot("first token")
bot_2 = SimpleLongPollUserBot("second token")


@bot.message_handler(bot.command_filter(commands=["ping"]), bot.from_me_filter(False))
async def start(event: bot.SimpleBotEvent):
    await event.answer("pong")


clones = ClonesBot(bot, bot_2)

clones.run_all_bots()
```

Ошибка:
```
Task exception was never retrieved
future: <Task finished name='Task-1' coro=<BaseSimpleLongPollBot.run() done, defined at /data/user/0/ru.iiec.pydroid3/files/aarch64-linux-android/lib/python3.8/site-packages/vkwave/bots/addons/easy/base_easy_bot.py:300> exception=TypeError('start() takes 1 positional argument but 2 were given')>
Traceback (most recent call last):
  File "/data/user/0/ru.iiec.pydroid3/files/aarch64-linux-android/lib/python3.8/site-packages/vkwave/bots/addons/easy/base_easy_bot.py", line 303, in run
    await self._lp.start(ignore_errors)
TypeError: start() takes 1 positional argument but 2 were given
Task exception was never retrieved
future: <Task finished name='Task-2' coro=<BaseSimpleLongPollBot.run() done, defined at /data/user/0/ru.iiec.pydroid3/files/aarch64-linux-android/lib/python3.8/site-packages/vkwave/bots/addons/easy/base_easy_bot.py:300> exception=TypeError('start() takes 1 positional argument but 2 were given')>
Traceback (most recent call last):
  File "/data/user/0/ru.iiec.pydroid3/files/aarch64-linux-android/lib/python3.8/site-packages/vkwave/bots/addons/easy/base_easy_bot.py", line 303, in run
    await self._lp.start(ignore_errors)
TypeError: start() takes 1 positional argument but 2 were given
```

**Comment by kesha1225** [comment]
Нужно обновиться

```pip install https://github.com/fscdev/vkwave/archive/master.zip -U```
